# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
#  html5:
#    text: 官网
#    url: http://www.kotlinandroid.net/website
  home:
    text: 主页
    url: /
  archives:
    text: 文章
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  book:
    text: 书籍
    url: /books
  film:
    text: 电影
    url: /movies
  photo:
    text: 相册
    url: https://www.instagram.com/itgoyo1991/
  envelope:
    text: 邮件
    url: "Mailto:itgoyo@kotlinandroid.net"
  calendar:
    text: 时间轴
    url: http://www.kotlinandroid.net/timeline
  github:
    text: Github
    url: https://github.com/itgoyo
  file-text:
    text: Résumé
    url: http://www.kotlinandroid.net/resume
  android:
    text: 官方培训课程
    url: http://hukai.me/android-training-course-in-chinese/index.html

#  github:
#    url: https://github.com/enbandari
#    target: _blank
#  weibo:
#    url: http://www.weibo.com/ysweb
#    target: _blank
#  link:
#    text: 知乎
#    url: https://zhuanlan.zhihu.com/bennyhuo
#    target: _blank
#  cube:
#    text: Println
#    url: http://www.println.net
#    target: _blank
#  star:
#    text: ice1000
#    url: http://ice1000.org
#    target: _blank


rss: /atom.xml

# 你的头像url
avatar: /img/xtqr.jpg
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: /img/kotlin.png

# email
email:  itgoyo@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签
archives_title: 所有文章
categories_title: 分类
author_title: 所有作者

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 奖励一杯咖啡!

  alipay: /assets/img/alipay.jpg     #支付宝，关闭设为 false
  wechat: /assets/img/wechat.jpg     #微信，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页版权声明内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
copyright: 转载请注明出处 #：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: 1261686164

# 百度统计，如要开启，改为你的 key
baidu_tongji: false
baidu_push: true

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: true

# less
less:
  compress: true
  paths:
    - source/css/style.less


#comments:
#
# 是否开启多说评论，填写你在多说创建的站点二级域名
# duoshuo: ysblog
# 是否开启多说评论计数（该服务不稳定）
# duoshuo_count: false
# 使用 disqus 时关闭多说评论
# disqus_shortname: itgoyo
# 是否开启友言评论, 填写友言用户id
# uyan_uid: false # 2130248

# yungentie: 0263eabe3b1b46709556eda1c39750be


# 以下评论插件开启一个即可
# 是否开启 disqus
# disqus_shortname: falsee
disqus_shortname: itgoyo
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否开启网易云跟帖， 填写app sdk中的app key
wangyi_ygt: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment:
  enable: true
  owner: itgoyo
  repo: itgoyo.github.io
  client_id: 464e7c112346fd6daabb
  client_secret: 3f78aa47b168a9788b888238a610dff1ac6e51ac




# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: http://www.kotlinandroid.net

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 我们是来自全国各地的Github爱好者，期待你的加入！

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

# 动态定义title
title_change:
normal: ｡◕‿◕｡
leave: 点我有惊喜...

# 设置为 true 发布后将使用 unpkg cdn
cdn: false
